version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
  nginx:
    image: nginx
    ports:
      - "80:8080"
    volumes:
      - ./nginx_p6:/etc/nginx
    depends_on:
      - server
