.PHONY: cpw 
#
cpw:
	@sudo cp save-configs.sh /etc/cron.weekly/save-configs

.PHONY: cpm 
#
cpm:
	@sudo cp save-configs.sh /etc/cron.monthly/save-configs

.PHONY: lsw
# List local cron.weekly dir
lsw:
	@ls -la /etc/cron.weekly/

.PHONY: lsm
# List local cron.monthly dir
lsm:
	@ls -la /etc/cron.monthly/


