version: '3.9'

volumes:
  data:

services:
  mumble:
    container_name: "mumble"
    image: mumble
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - data:/etc/mumble
    ports:
      - 64738:64738
      - 64738:64738/udp
